// Generated by CoffeeScript 1.4.0
(function() {
  var MyGovLoader,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  MyGovLoader = (function() {

    MyGovLoader.prototype.rootUrl = 'http://localhost:4000/';

    MyGovLoader.prototype.scrollTrigger = 80;

    MyGovLoader.prototype.loaded = false;

    MyGovLoader.prototype.state = 'hidden';

    MyGovLoader.prototype.id = 'myGovBar';

    MyGovLoader.prototype.style = {
      position: 'fixed',
      bottom: 0,
      left: 0,
      background: 'transparent',
      width: '20%',
      height: '110px',
      border: 0,
      'z-index': 9999999,
      overflow: 'hidden'
    };

    function MyGovLoader() {
      this.onScroll = __bind(this.onScroll, this);
      this.addEvent(document, 'scroll', this.onScroll);
    }

    MyGovLoader.prototype.addEvent = function(el, event, func) {
      if (el.addEventListener) {
        return el.addEventListener(event, func, false);
      } else if (el.attachEvent) {
        return el.attachEvent("on" + event, func);
      }
    };

    MyGovLoader.prototype.onScroll = function() {
      if (this.offsetBottom() > this.scrollTrigger) {
        return this.show();
      } else {
        return this.hide();
      }
    };

    MyGovLoader.prototype.positionTop = function() {
      return window.pageYOffset || body.scrollTop || html.scrollTop;
    };

    MyGovLoader.prototype.pageHeight = function() {
      return Math.max(Math.max(document.body.scrollHeight, document.documentElement.scrollHeight), Math.max(document.body.offsetHeight, document.documentElement.offsetHeight), Math.max(document.body.clientHeight, document.documentElement.clientHeight));
    };

    MyGovLoader.prototype.windowHeight = function() {
      return window.innerHeight || html.clientHeight || body.clientHeight || screen.availHeight;
    };

    MyGovLoader.prototype.offsetBottom = function() {
      return 100 * (this.positionTop() + this.windowHeight()) / this.pageHeight();
    };

    MyGovLoader.prototype.load = function() {
      var el, key, value, _ref;
      el = document.createElement('iframe');
      el.id = this.id;
      el.src = this.rootUrl + 'mygov-bar.html';
      _ref = this.style;
      for (key in _ref) {
        value = _ref[key];
        el.style[key] = value;
      }
      document.body.appendChild(el);
      return this.loaded = true;
    };

    MyGovLoader.prototype.setWidth = function(width) {
      return document.getElementById(this.id).style.width = width;
    };

    MyGovLoader.prototype.show = function() {
      if (this.state === 'shown') {
        return;
      }
      if (!this.loaded) {
        this.load();
      }
      this.setWidth('20%');
      return this.state = 'shown';
    };

    MyGovLoader.prototype.hide = function() {
      if (this.state === 'hidden') {
        return;
      }
      console.log('hiding');
      this.setWidth('0px');
      return this.state = 'hidden';
    };

    return MyGovLoader;

  })();

  window.MyGovLoader = new MyGovLoader();

}).call(this);
