// Generated by CoffeeScript 1.3.3
(function() {
  var MyGovBar,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  MyGovBar = (function() {

    function MyGovBar() {
      this.toggle = __bind(this.toggle, this);

      this.show = __bind(this.show, this);

      this.hide = __bind(this.hide, this);

    }

    MyGovBar.prototype.el = $("#bar");

    MyGovBar.prototype.init = function() {
      $("#logo").click(this.toggle);
      $('.toggle_pane').click(this.togglePane);
      return this.toggle();
    };

    MyGovBar.prototype.hide = function() {
      var _this = this;
      return $('.popout').animate({
        'height': 0
      }, 200).promise().done(function() {
        $('.expanded').removeClass('expanded');
        return _this.el.animate({
          width: "0%"
        }, 1000);
      });
    };

    MyGovBar.prototype.show = function() {
      return this.el.animate({
        width: "75%"
      }, 1000);
    };

    MyGovBar.prototype.toggle = function() {
      if (this.el.css('width') === "0px") {
        return this.show();
      } else {
        return this.hide();
      }
    };

    MyGovBar.prototype.togglePane = function(e) {
      e.preventDefault;
      if ($(this).parent().hasClass('expanded')) {
        this.hidePane($(this).parent());
      } else {
        this.showPane($(this).parent());
      }
      return false;
    };

    MyGovBar.prototype.showPane = function(pane) {
      var popout;
      popout = $(pane).children('.popout');
      $(popout).clearQueue();
      $(popout).css('left', $(this).parent().css('left'));
      $(popout).animate({
        height: "300px"
      }, 1000);
      return $(pane).addClass('expanded');
    };

    MyGovBar.prototype.hidePane = function(pane) {
      $(pane).children('.popout').animate({
        height: 0
      }, 1000);
      return $(pane).removeClass('expanded');
    };

    return MyGovBar;

  })();

  $(document).ready(function() {
    window.myGovBar = new MyGovBar();
    return myGovBar.init();
  });

}).call(this);
