// Generated by CoffeeScript 1.4.0
(function() {
  var script;

  script = document.createElement('script');

  script.src = "{{ site.url }}/embed-code.js";

  document.body.appendChild(script);

}).call(this);
