// Generated by CoffeeScript 1.4.0
(function() {
  var script;

  script = document.createElement('script');

  script.src = "http://localhost:4000/mygov-bar.js";

  document.body.appendChild(script);

}).call(this);
