// Generated by CoffeeScript 1.4.0
var init, maybeLoadJq;

init = function() {
  return jQuery(document).ready(function($) {
    return $('body').append('<script src="http://gsa-ocsit.github.com/mygov-bar/embed-code.js"></script>');
  });
};

maybeLoadJq = function() {
  var jQ;
  if (!(typeof jQuery !== "undefined" && jQuery !== null)) {
    jQ = document.createElement('script');
    jQ.type = 'text/javascript';
    jQ.onload = jQ.onreadystatechange = init;
    jQ.src = '//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js';
    return document.body.appendChild(jQ);
  } else {
    return init();
  }
};

if (window.addEventListener) {
  window.addEventListener('load', maybeLoadJq, false);
} else if (window.attachEvent) {
  window.attachEvent('onload', maybeLoadJq);
}
