// Generated by CoffeeScript 1.4.0
(function() {
  var script;

  script = document.createElement('script');

  script.src = "http://gsa-ocsit.github.com/mygov-bar/mygov-bar.js";

  document.body.appendChild(script);

}).call(this);
