// Generated by CoffeeScript 1.3.3
(function() {
  var script;

  script = document.createElement('script');

  script.src = "http://gsa-ocsit.github.com/mygov-bar/embed-code.js";

  document.body.appendChild(script);

}).call(this);
