// Generated by CoffeeScript 1.3.3
(function() {
  var script;

  script = document.createElement('script');

  script.src = "http://localhost:4000/embed-code.js";

  document.body.appendChild(script);

  console.log('injected');

}).call(this);
